sudo: true
dist: trusty

# Install the apt prerequisites
addons:
  apt:
    packages:
      - wget
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0
  - wget -O /tmp/hugo_0.38.2_Linux-64bit.deb https://github.com/gohugoio/hugo/releases/download/v0.38.2/hugo_0.38.2_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo_0.38.2_Linux-64bit.deb

# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: site
  target-branch: master
