dist: trusty

language: node_js

node_js:
  "8"

# Build the website
script:
  - npx antora site.yml --stacktrace

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: site
  target-branch: master
