site:
  title: Terra-Farm - The Terraform Community
  url: https://terra-farm.github.io
  start_page: main::index.adoc 
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/terra-farm/terraform-provider-xenserver.git
    branches: master
  - url: https://github.com/terra-farm/terraform-provider-xenorchestra.git
    branches: master
  - url: https://github.com/terra-farm/terraform-provider-virtualbox.git
    branches: 
      - master
      - v0.2.0
ui:
  bundle:
    url: https://github.com/terra-farm/terra-farm.ui/releases/download/v0.0.3/bundle.zip
    snapshot: true
  output_dir: brand
